description = "Tiny base image (Ubuntu Noble Numbar build image, distroless-like run image) with no buildpacks included. To use, specify buildpacks at build time."

[lifecycle]
  version = "0.19.6"

[stack]
  build-image = "docker.io/paketobuildpacks/build-noble-tiny:0.0.1"
  id = "io.buildpacks.stacks.noble.tiny"
  run-image = "index.docker.io/paketobuildpacks/run-noble-tiny:latest"
  run-image-mirrors = []

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
